spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: com.demo.taxiApi.common.SQLiteDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:taxiApiDB
    username: sa
    password: sa
server:
  port: 9876